### ISSUE TITLE
static compilation fails with GCC 5.4.0 on ubuntu 16.04

### ISSUE THREAD

**Issue by pankajbansal3073** [rhboot/efivar#102]
build command: make CROSS_COMPILE=aarch64-linux-gnu- prefix=/home/b58867/Desktop/ls1043ardb/efivar/efivar_arm64 static

compilation error: 
aarch64-linux-gnu-gcc -O2 -flto -g3 -I/home/b58867/Desktop/ls1043ardb/efivar/src/include/  -specs=/home/b58867/Desktop/ls1043ardb/efivar/gcc.specs  -L.   -Wl,-z,muldefs    -static  -o efivar-static efivar.c dp.static.o dp-acpi.static.o dp-hw.static.o dp-media.static.o dp-message.static.o efivarfs.static.o error.static.o export.static.o guid.static.o guids.static.o guid-symbols.static.o lib.static.o vars.static.o -ldl
guid.c:112:24: error: type of ‘efi_well_known_guids_end’ does not match original declaration [-Werror]
 extern struct guidname efi_well_known_guids_end
                        ^
efivar.c:490:28: note: previously declared here
    extern struct guidname *efi_well_known_guids_end;
                            ^
efivar.c:489:27: error: type of ‘efi_well_known_guids’ does not match original declaration [-Werror]
    extern struct guidname efi_well_known_guids[];
                           ^
guid.c:108:24: note: previously declared here
 extern struct guidname efi_well_known_guids
                        ^
lto1: all warnings being treated as errors
lto-wrapper: fatal error: aarch64-linux-gnu-gcc returned 1 exit status

**Comment by vathpela** [comment]
I'm closing this - it works for me with clang on Fedora 28.  If I'm wrong and it's not fixed, please do feel free to re-open it.
