### ISSUE TITLE
Cut new release with NVME fix

### ISSUE THREAD

**Issue by robbat2** [rhboot/efivar#121]
Can you please cut a new release that includes the NVME fix from commit d8d7e54fe01a7a255e649a7734820800edf82?

This would avoid reports like:
https://github.com/hughsie/fwupd/issues/709
https://www.reddit.com/r/linux/comments/9b7doe/psa_beware_when_updating_your_thinkpad_uefi/

Confirmed on my X1 Carbon 6th generation (NVME boot device, efi entries toasted on firmware upgrade)

**Comment by incognico** [comment]
I second this.

efibootmgr with efivar-libs-36 does not work on my hardware. With efivar-libs-35 it works fine.

v36 error msg:
![asdf](https://user-images.githubusercontent.com/2098066/45410528-36fedf00-b672-11e8-9e30-a7ca57395622.jpg)

I've not tested it but the EUI commit looks promising, looking at the error msg. v36 probably won't work on a large variety of hardware.

**Comment by Piraty** [comment]
i also ran into this today, using efivar-36. building from current master (as of cff3564), it solved my issue (https://github.com/rhboot/efibootmgr/issues/99).

**Comment by gentoochainsaw** [comment]
Please roll a new release.

**Comment by Keruspe** [comment]
@vathpela Any news on this?

**Comment by joakim-tjernlund** [comment]
New release please

**Comment by vathpela** [comment]
Should be fixed in https://github.com/rhboot/efivar/releases/tag/37 , if not, please re-open this issue.
