### ISSUE TITLE
“ fail to set new efi boot tartget” will occurs when install os under UEFI mode with rste raid.

### ISSUE THREAD

**Issue by xiaochunlee** [rhboot/efivar#122]
When I fresh install the RHEL7.6 under the mode of rste raid,The following error occurred while installing the boot loader, that show a dialog box  that prompt "fail to set new  efi boot tartget" , But we can continue complete to the OS installation.
 
I have traced the program of the efiboogmgr, the process show like below:
 efiboogmgr.c ->main()->make_var()->make_linux_load_option()->efi_generate_file_device_path_from_esp()->efi_va_generate_file_device_path_from_esp()->device_get()-->
 
In the function of device_get, it will read the device file by the function of sysfs_readlink, the function show as below:
 rc = sysfs_readlink(&tmpbuf, "block/%s/device", dev->disk_name); 
 
Finally,this function have not got the file of device ,such as /sys/block/md127/device，The OS driver haven't created the file named device under the directory /sys/block/md127/,So all program of efibootmgr will exit with some errors.
 
And we can see different types of devices will get the disk_name with different methods  in function set_disk_and_part_name. So how do we get the device of the virtual device? Such as the VMD.

**Comment by xiaochunlee** [comment]
> Hopefully, this commit should fix this issue:
> [576f55b](https://github.com/rhboot/efivar/commit/576f55b02d9ec478bd5157352c884e3543bcca58)
Thanks,I have finded out the similar bug in Red Hat bugzilla，this is the link：https://bugzilla.redhat.com/show_bug.cgi?id=1602414

**Comment by vathpela** [comment]
Should be fixed in https://github.com/rhboot/efivar/releases/tag/37 , if not, please re-open this issue.
