### ISSUE TITLE
37: abicheck fails

### ISSUE THREAD

**Issue by kloczek** [rhboot/efivar#128]
<pre>[tkloczko@domek efivar-37]$ make abicheck
make -C src abicheck
make[1]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/efivar-37/src&apos;
make -f /home/tkloczko/rpmbuild/BUILD/efivar-37/src/Make.deps deps SOURCES=&quot;crc32.c creator.c disk.c gpt.c loadopt.c path-helpers.c linux.c linux-acpi-root.c linux-sas.c linux-emmc.c linux-ata.c linux-pci-root.c linux-sata.c linux-md.c linux-acpi.c linux-soc-root.c linux-nvme.c linux-scsi.c linux-virtblk.c linux-pmem.c linux-pci.c linux-i2o.c dp.c dp-acpi.c dp-hw.c dp-media.c dp-message.c efivarfs.c error.c export.c guid.c guids.S guid-symbols.c lib.c vars.c makeguids.c guid.c include/efivar/efivar-guids.h include/efivar/efivar.h include/efivar/efiboot.h include/efivar/efiboot-loadopt.h include/efivar/efivar-dp.h include/efivar/efiboot-creator.h include/efivar/efivar-guids.h guid-symbols.c efivar.c&quot;
make[2]: Entering directory &apos;/home/tkloczko/rpmbuild/BUILD/efivar-37/src&apos;
make[2]: Nothing to be done for &apos;deps&apos;.
make[2]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/efivar-37/src&apos;
abidiff \
	--suppr abignore \
	--headers-dir2 /home/tkloczko/rpmbuild/BUILD/efivar-37/src/include/efivar/ \
	libefivar.abixml \
	libefivar.so
Functions changes summary: 0 Removed, 32 Changed (9 filtered out), 0 Added (1 filtered out) functions
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable

32 functions with some indirect sub-type change:

  [C]&apos;function int _efi_set_variable(efi_guid_t, const char*, uint8_t*, size_t, uint32_t, efi_guid_t, const char*, uint8_t*, size_t, uint32_t)&apos; at string.h:46:1 has some indirect sub-type changes:
    parameter 6 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 7 of type &apos;const char*&apos; was removed
    parameter 8 of type &apos;uint8_t*&apos; was removed
    parameter 9 of type &apos;typedef size_t&apos; was removed
    parameter 10 of type &apos;typedef uint32_t&apos; was removed

  [C]&apos;function int _efi_set_variable_mode(efi_guid_t, const char*, uint8_t*, size_t, uint32_t, mode_t, efi_guid_t, const char*, uint8_t*, size_t, uint32_t, mode_t)&apos; at string.h:70:1 has some indirect sub-type changes:
    Please note that the exported symbol of this function is efi_set_variable@@LIBEFIVAR_0.24
    parameter 7 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 8 of type &apos;const char*&apos; was removed
    parameter 9 of type &apos;uint8_t*&apos; was removed
    parameter 10 of type &apos;typedef size_t&apos; was removed
    parameter 11 of type &apos;typedef uint32_t&apos; was removed
    parameter 12 of type &apos;typedef mode_t&apos; was removed

  [C]&apos;function int _efi_set_variable_variadic(efi_guid_t, const char*, uint8_t*, size_t, uint32_t, efi_guid_t, const char*, uint8_t*, size_t, uint32_t)&apos; at string.h:58:1 has some indirect sub-type changes:
    parameter 6 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 7 of type &apos;const char*&apos; was removed
    parameter 8 of type &apos;uint8_t*&apos; was removed
    parameter 9 of type &apos;typedef size_t&apos; was removed
    parameter 10 of type &apos;typedef uint32_t&apos; was removed

  [C]&apos;function int efi_chmod_variable(efi_guid_t, const char*, mode_t, efi_guid_t, const char*, mode_t)&apos; at string.h:205:1 has some indirect sub-type changes:
    parameter 4 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 5 of type &apos;const char*&apos; was removed
    parameter 6 of type &apos;typedef mode_t&apos; was removed

  [C]&apos;function int efi_del_variable(efi_guid_t, const char*, efi_guid_t, const char*)&apos; at string.h:111:1 has some indirect sub-type changes:
    parameter 3 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 4 of type &apos;const char*&apos; was removed

  [C]&apos;function int efi_error_get(unsigned int, char** const, char** const, int*, char** const, int*, unsigned int, char** const, char** const, int*, char** const, int*)&apos; at ioctl.h:56:1 has some indirect sub-type changes:
    parameter 7 of type &apos;unsigned int&apos; was removed
    parameter 8 of type &apos;char** const&apos; was removed
    parameter 9 of type &apos;char** const&apos; was removed
    parameter 10 of type &apos;int*&apos; was removed
    parameter 11 of type &apos;char** const&apos; was removed
    parameter 12 of type &apos;int*&apos; was removed

  [C]&apos;function FILE* efi_get_logfile()&apos; at ioctl.h:165:1 has some indirect sub-type changes:
    return type changed:
      in pointed to type &apos;typedef FILE&apos; at FILE.h:7:1:
        underlying type &apos;struct _IO_FILE&apos; at struct_FILE.h:49:1 changed:
          type size hasn&apos;t changed
          1 data member insertion:
            &apos;_IO_lock_t* _IO_FILE::_lock&apos;, at offset 1088 (in bits) at struct_FILE.h:81:1
          no data member changes (2 filtered);

  [C]&apos;function int efi_get_next_variable_name(efi_guid_t**, char**, efi_guid_t**, char**)&apos; at string.h:188:1 has some indirect sub-type changes:
    parameter 3 of type &apos;efi_guid_t**&apos; was removed
    parameter 4 of type &apos;char**&apos; was removed

  [C]&apos;function int efi_get_variable(efi_guid_t, const char*, uint8_t**, size_t*, uint32_t*, efi_guid_t, const char*, uint8_t**, size_t*, uint32_t*)&apos; at string.h:128:1 has some indirect sub-type changes:
    parameter 6 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 7 of type &apos;const char*&apos; was removed
    parameter 8 of type &apos;uint8_t**&apos; was removed
    parameter 9 of type &apos;size_t*&apos; was removed
    parameter 10 of type &apos;uint32_t*&apos; was removed

  [C]&apos;function int efi_get_variable_attributes(efi_guid_t, const char*, uint32_t*, efi_guid_t, const char*, uint32_t*)&apos; at string.h:146:1 has some indirect sub-type changes:
    parameter 4 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 5 of type &apos;const char*&apos; was removed
    parameter 6 of type &apos;uint32_t*&apos; was removed

  [C]&apos;function int efi_get_variable_size(efi_guid_t, const char*, size_t*, efi_guid_t, const char*, size_t*)&apos; at string.h:171:1 has some indirect sub-type changes:
    parameter 4 of type &apos;typedef efi_guid_t&apos; was removed
    parameter 5 of type &apos;const char*&apos; was removed
    parameter 6 of type &apos;size_t*&apos; was removed

  [C]&apos;function int efi_guid_cmp(const efi_guid_t*, const efi_guid_t*)&apos; at ioctl.h:34:1 has some indirect sub-type changes:
    parameter 1 of type &apos;const efi_guid_t*&apos; changed:
      entity changed from &apos;const efi_guid_t*&apos; to &apos;void* const&apos;
      type size hasn&apos;t changed
    parameter 2 of type &apos;const efi_guid_t*&apos; changed:
      entity changed from &apos;const efi_guid_t*&apos; to &apos;void* const&apos;
      type size hasn&apos;t changed

  [C]&apos;function int efi_guid_to_name(efi_guid_t*, char**, efi_guid_t*, char**)&apos; at ioctl.h:146:1 has some indirect sub-type changes:
    parameter 3 of type &apos;efi_guid_t*&apos; was removed
    parameter 4 of type &apos;char**&apos; was removed

  [C]&apos;function int efi_guid_to_symbol(efi_guid_t*, char**, efi_guid_t*, char**)&apos; at ioctl.h:161:1 has some indirect sub-type changes:
    parameter 3 of type &apos;efi_guid_t*&apos; was removed
    parameter 4 of type &apos;char**&apos; was removed

  [C]&apos;function int efi_str_to_guid(const char*, efi_guid_t*, const char*, efi_guid_t*)&apos; at ioctl.h:50:1 has some indirect sub-type changes:
    parameter 3 of type &apos;const char*&apos; was removed
    parameter 4 of type &apos;efi_guid_t*&apos; was removed

  [C]&apos;function ssize_t efi_variable_get_data(efi_variable_t*, uint8_t**, size_t*, efi_variable_t*, uint8_t**, size_t*)&apos; at errno.h:286:1 has some indirect sub-type changes:
    parameter 4 of type &apos;efi_variable_t*&apos; was removed
    parameter 5 of type &apos;uint8_t**&apos; was removed
    parameter 6 of type &apos;size_t*&apos; was removed

  [C]&apos;function int efi_variable_get_guid(efi_variable_t*, efi_guid_t**, efi_variable_t*, efi_guid_t**)&apos; at errno.h:261:1 has some indirect sub-type changes:
    parameter 3 of type &apos;efi_variable_t*&apos; was removed
    parameter 4 of type &apos;efi_guid_t**&apos; was removed

  [C]&apos;function char* efi_variable_get_name(efi_variable_t*, efi_variable_t*)&apos; at errno.h:243:1 has some indirect sub-type changes:
    parameter 2 of type &apos;efi_variable_t*&apos; was removed

  [C]&apos;function int efi_variable_set_data(efi_variable_t*, uint8_t*, size_t, efi_variable_t*, uint8_t*, size_t)&apos; at errno.h:273:1 has some indirect sub-type changes:
    parameter 4 of type &apos;efi_variable_t*&apos; was removed
    parameter 5 of type &apos;uint8_t*&apos; was removed
    parameter 6 of type &apos;typedef size_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_acpi_hid(uint8_t*, ssize_t, uint32_t, uint32_t, uint8_t*, ssize_t, uint32_t, uint32_t)&apos; has some indirect sub-type changes:
    parameter 5 of type &apos;uint8_t*&apos; was removed
    parameter 6 of type &apos;typedef ssize_t&apos; was removed
    parameter 7 of type &apos;typedef uint32_t&apos; was removed
    parameter 8 of type &apos;typedef uint32_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_atapi(uint8_t*, ssize_t, uint16_t, uint16_t, uint16_t, uint8_t*, ssize_t, uint16_t, uint16_t, uint16_t)&apos; at dirent.h:766:1 has some indirect sub-type changes:
    parameter 6 of type &apos;uint8_t*&apos; was removed
    parameter 7 of type &apos;typedef ssize_t&apos; was removed
    parameter 8 of type &apos;typedef uint16_t&apos; was removed
    parameter 9 of type &apos;typedef uint16_t&apos; was removed
    parameter 10 of type &apos;typedef uint16_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_edd10(uint8_t*, ssize_t, uint32_t, uint8_t*, ssize_t, uint32_t)&apos; has some indirect sub-type changes:
    parameter 4 of type &apos;uint8_t*&apos; was removed
    parameter 5 of type &apos;typedef ssize_t&apos; was removed
    parameter 6 of type &apos;typedef uint32_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_generic(uint8_t*, ssize_t, uint8_t, uint8_t, ssize_t, uint8_t*, ssize_t, uint8_t, uint8_t, ssize_t)&apos; has some indirect sub-type changes:
    parameter 6 of type &apos;uint8_t*&apos; was removed
    parameter 7 of type &apos;typedef ssize_t&apos; was removed
    parameter 8 of type &apos;typedef uint8_t&apos; was removed
    parameter 9 of type &apos;typedef uint8_t&apos; was removed
    parameter 10 of type &apos;typedef ssize_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_hd(uint8_t*, ssize_t, uint32_t, uint64_t, uint64_t, uint8_t*, uint8_t, uint8_t, uint8_t*, ssize_t, uint32_t, uint64_t, uint64_t, uint8_t*, uint8_t, uint8_t)&apos; has some indirect sub-type changes:
    parameter 9 of type &apos;uint8_t*&apos; was removed
    parameter 10 of type &apos;typedef ssize_t&apos; was removed
    parameter 11 of type &apos;typedef uint32_t&apos; was removed
    parameter 12 of type &apos;typedef uint64_t&apos; was removed
    parameter 13 of type &apos;typedef uint64_t&apos; was removed
    parameter 14 of type &apos;uint8_t*&apos; was removed
    parameter 15 of type &apos;typedef uint8_t&apos; was removed
    parameter 16 of type &apos;typedef uint8_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_ipv4(uint8_t*, ssize_t, uint32_t, uint32_t, uint32_t, uint32_t, uint16_t, uint16_t, uint16_t, int, uint8_t*, ssize_t, uint32_t, uint32_t, uint32_t, uint32_t, uint16_t, uint16_t, uint16_t, int)&apos; at dirent.h:671:1 has some indirect sub-type changes:
    parameter 11 of type &apos;uint8_t*&apos; was removed
    parameter 12 of type &apos;typedef ssize_t&apos; was removed
    parameter 13 of type &apos;typedef uint32_t&apos; was removed
    parameter 14 of type &apos;typedef uint32_t&apos; was removed
    parameter 15 of type &apos;typedef uint32_t&apos; was removed
    parameter 16 of type &apos;typedef uint32_t&apos; was removed
    parameter 17 of type &apos;typedef uint16_t&apos; was removed
    parameter 18 of type &apos;typedef uint16_t&apos; was removed
    parameter 19 of type &apos;typedef uint16_t&apos; was removed
    parameter 20 of type &apos;int&apos; was removed

  [C]&apos;function ssize_t efidp_make_mac_addr(uint8_t*, ssize_t, uint8_t, const uint8_t* const, ssize_t, uint8_t*, ssize_t, uint8_t, const uint8_t* const, ssize_t)&apos; at dirent.h:650:1 has some indirect sub-type changes:
    parameter 6 of type &apos;uint8_t*&apos; was removed
    parameter 7 of type &apos;typedef ssize_t&apos; was removed
    parameter 8 of type &apos;typedef uint8_t&apos; was removed
    parameter 9 of type &apos;const uint8_t* const&apos; was removed
    parameter 10 of type &apos;typedef ssize_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_nvdimm(uint8_t*, ssize_t, efi_guid_t*, uint8_t*, ssize_t, efi_guid_t*)&apos; at dirent.h:814:1 has some indirect sub-type changes:
    parameter 4 of type &apos;uint8_t*&apos; was removed
    parameter 5 of type &apos;typedef ssize_t&apos; was removed
    parameter 6 of type &apos;efi_guid_t*&apos; was removed

  [C]&apos;function ssize_t efidp_make_nvme(uint8_t*, ssize_t, uint32_t, uint8_t*, uint8_t*, ssize_t, uint32_t, uint8_t*)&apos; at dirent.h:718:1 has some indirect sub-type changes:
    parameter 5 of type &apos;uint8_t*&apos; was removed
    parameter 6 of type &apos;typedef ssize_t&apos; was removed
    parameter 7 of type &apos;typedef uint32_t&apos; was removed
    parameter 8 of type &apos;uint8_t*&apos; was removed

  [C]&apos;function ssize_t efidp_make_pci(uint8_t*, ssize_t, uint8_t, uint8_t, uint8_t*, ssize_t, uint8_t, uint8_t)&apos; has some indirect sub-type changes:
    parameter 5 of type &apos;uint8_t*&apos; was removed
    parameter 6 of type &apos;typedef ssize_t&apos; was removed
    parameter 7 of type &apos;typedef uint8_t&apos; was removed
    parameter 8 of type &apos;typedef uint8_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_sas(uint8_t*, ssize_t, uint64_t, uint8_t*, ssize_t, uint64_t)&apos; at dirent.h:789:1 has some indirect sub-type changes:
    parameter 4 of type &apos;uint8_t*&apos; was removed
    parameter 5 of type &apos;typedef ssize_t&apos; was removed
    parameter 6 of type &apos;typedef uint64_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_sata(uint8_t*, ssize_t, uint16_t, int16_t, uint16_t, uint8_t*, ssize_t, uint16_t, int16_t, uint16_t)&apos; at dirent.h:744:1 has some indirect sub-type changes:
    parameter 6 of type &apos;uint8_t*&apos; was removed
    parameter 7 of type &apos;typedef ssize_t&apos; was removed
    parameter 8 of type &apos;typedef uint16_t&apos; was removed
    parameter 9 of type &apos;typedef int16_t&apos; was removed
    parameter 10 of type &apos;typedef uint16_t&apos; was removed

  [C]&apos;function ssize_t efidp_make_scsi(uint8_t*, ssize_t, uint16_t, uint16_t, uint8_t*, ssize_t, uint16_t, uint16_t)&apos; at dirent.h:700:1 has some indirect sub-type changes:
    parameter 5 of type &apos;uint8_t*&apos; was removed
    parameter 6 of type &apos;typedef ssize_t&apos; was removed
    parameter 7 of type &apos;typedef uint16_t&apos; was removed
    parameter 8 of type &apos;typedef uint16_t&apos; was removed

make[1]: *** [/home/tkloczko/rpmbuild/BUILD/efivar-37/Make.rules:31: libefivar.abicheck] Error 4
make[1]: Leaving directory &apos;/home/tkloczko/rpmbuild/BUILD/efivar-37/src&apos;
make: *** [Makefile:24: abicheck] Error 2
</pre>

**Comment by vathpela** [comment]
This happens because different versions of libabigail don't present quite the same results.  For now, the solution is this:
- check out the previous tagged release on a branch
- 'make abiupdate'
- commit the .abixml differences
- switch back to the branch you want to run abicheck on
- cherry-pick the abixml update commit
- run 'make abicheck'
This generally works if we haven't changed the ABI through anything but additions, and shows us where we've done anything else.
