### ISSUE TITLE
Usage of --fromfile unclear

### ISSUE THREAD

**Issue by jwatt** [rhboot/efivar#129]
The man page states that there is a --fromfile option but says nothing about the format of the file that is to be specified. It would be helpful if it would do so.

**Comment by rbisewski** [comment]
Specifically, I think it is the contents of the variable itself, in whatever format that variable is using; the `--print --name xxx` can probably give you a good idea.

In general the manpage for efivar could use a quick rewrite, so I will probably make a pull request later today.
