### ISSUE TITLE
Shouldn't use -Werror

### ISSUE THREAD

**Issue by rossburton** [rhboot/efivar#131]
Please don't mandate the use of `-Werror`, because if someone upgrades gcc before you and gets new warnings, then the build breaks.  For example the gcc8 fallthrough warnings, #123.

I appreciate that as a maintainer you'd like to use `-Werror` to catch warnings, but please don't force everyone to use it.

**Comment by vathpela** [comment]
This is addressed as part of PR #140.  -Werror is still on by default, but it is now be very, very easy to override.
