### ISSUE TITLE
Unable to use efibootmgr on a NVMe system

### ISSUE THREAD

**Issue by remyoudompheng** [rhboot/efivar#135]
I am unable to use efibootmgr on a NVMe system running Debian 10, making bootloader install ineffective (or at least very inconvenient).
Debian 10 runs Linux 4.19.67 and efibootmgr 15 and efivar 37.

```
# efibootmgr --create --loader /EFI/debian/grubx64.efi --label debian -v3 --disk /dev/nvme0n1p1
Could not prepare Boot variable: No such file or directory
error trace:
linux.c:390 device_get(): readlink of /sys/block/(null)/device failed: No such file or directory
creator.c:155 open_disk(): could not open disk: No such file or directory
...
```
(and same error with `--disk /dev/nvme0n1 --part 1`)

Trying to debug I observed the following pattern, which seems unexpected by function `set_disk_and_part_name`
```
# ls -l /dev/nvme0n1p1
brw-rw---- 1 root disk 259, 6 Sep 10 15:06 /dev/nvme0n1p1
# ls -ld /sys/dev/block/259:6
lrwxrwxrwx 1 root root 0 Sep 10 15:10 /sys/dev/block/259:6 -> ../../devices/virtual/nvme-subsystem/nvme-subsys0/nvme0n1/nvme0n1p1
```

**Comment by vathpela** [comment]
Can you try https://github.com/rhboot/efivar/pull/139 and see if this fixes it?
