### ISSUE TITLE
Any plans to make new release?

### ISSUE THREAD

**Issue by kloczek** [rhboot/efivar#137]
I think that it would be good to flush currently committed changes and make new release :)

**Comment by joakim-tjernlund** [comment]
yes please

**Comment by dvzrv** [comment]
Hi! I maintain efivar for Arch Linux.

@vathpela there are quite substantial problems with building efivar v37 using current gcc versions.
Please release a new version

**Comment by ncopa** [comment]
We have [issues](https://gitlab.alpinelinux.org/alpine/aports/-/issues/11523) with Alpine Linux as well. A new release would be very helpful.

**Comment by PhysixProject** [comment]
Physix would appreciate a new release which incorporates commit 4e04afc

**Comment by PhysixProject** [comment]
ping!

**Comment by joakim-tjernlund** [comment]
96 commits since last release, surely there are "must have" fixes in there.

**Comment by rossburton** [comment]
Any update on a new release?  The choice is currently between the latest release (from 2018), or random SHAs from git which may or may not work.

**Comment by dvzrv** [comment]
@vathpela can we please have a new release? This ticket has been open asking for a new release for more than two years now and there has been no movement on the topic at all, yet new commits have been added as recent as one hour ago (at the time of writing).

On Arch Linux we have users with issues irt eMMC not being detected (https://bugs.archlinux.org/task/73231), rendering our installation medium on such devices unusable. It seems https://github.com/rhboot/efivar/commit/f0d3ed17ef3b2bbdfdff4dde12ec0a82d1ccdd33 would fix this, but it does not apply cleanly and it does not seem reasonable at all to start backporting fixes from a commit range of three years, given the potential side effects this might introduce.

**Comment by frozencemetery** [comment]
38 has been released.  Note that version 38 is literally a tag of what's in git, so it doesn't actually have any advantage over just carrying patches... but anyway, it's out now, so that's moot.

**Comment by oxr463** [comment]
Nice! Thank you
