### ISSUE TITLE
linux.c:406 device_get(): readlink of /sys/block/nvme0n1/device/driver failed: No such file or directory

### ISSUE THREAD

**Issue by superm1** [rhboot/efivar#138]
As reported in https://github.com/fwupd/fwupd/issues/1330 there are folks who have efivar 37 (IE have https://github.com/rhboot/efivar/commit/e83002b08aa6db57b90d89968ab8d34f6c7f73cf#diff-1422d881f587d22ee381976051c644c8) but are still encountering the error in the title.

Reports have happened across a few distros and kernel versions:
* Debian Buster (w/ 4.19)
* Gentoo (w/ 5.3)

**Comment by frozencemetery** [comment]
Does this still happen on main?

**Comment by frozencemetery** [comment]
Closing due to missing information.  If it still happens for you on main, please reopen/refile.
