### ISSUE TITLE
Upcoming release, in light of the "Could not parse device path: Invalid argument" bug?

### ISSUE THREAD

**Issue by SRGOM** [rhboot/efivar#151]
Hello, I recently hit this bug - https://bugzilla.redhat.com/show_bug.cgi?id=1773175

Seeing as this is pretty widespread and at the risk of sounding a freeloader, pretty much renders the "release" useless, are you guys planning on making a new release anytime? I ask this because downstream it's much easier to maintain software off defined releases as opposed to cherry-picking patches. 

Thank you for your work.

**Comment by ncopa** [comment]
This is a duplicate of #137
