### ISSUE TITLE
Fails to build with GCC 10

### ISSUE THREAD

**Issue by kevinoid** [rhboot/efivar#156]
Using GCC 10.1.0 (from the Debian `gcc-10` package version 10.1.0-6), building 36297ad (current `master`) by running `CC=gcc-10 make` fails with the following output:

    gcc-10 -Og -flto -g3 -Wall -Wextra  -Werror  -std=gnu11 -funsigned-char -fvisibility=hidden -specs=/tmp/efivar/src/include/gcc.specs -fno-merge-constants  -L.   -Wl,--add-needed -Wl,--build-id -Wl,--no-allow-shlib-undefined -Wl,--no-undefined-version -Wl,-z,now -Wl,-z,muldefs -Wl,-z,relro -Wl,--fatal-warnings     -DLIBEFIVAR_VERSION=37 -D_GNU_SOURCE -I/tmp/efivar/src/include/  -shared -Wl,-soname,libefivar.so.1 -Wl,--version-script=libefivar.map  \
      -o libefivar.so crc32.o dp.o dp-acpi.o dp-hw.o dp-media.o dp-message.o efivarfs.o error.o export.o guid.o guids.o guid-symbols.o lib.o vars.o -ldl 
    /tmp/ccoNwlWa.s: Assembler messages:
    /tmp/ccoNwlWa.s: Error: invalid attempt to declare external version name as default in symbol `efi_set_variable@@LIBEFIVAR_0.24'
    lto-wrapper: fatal error: gcc-10 returned 1 exit status
    compilation terminated.
    /usr/bin/ld: error: lto-wrapper failed
    collect2: error: ld returned 1 exit status
    make[1]: *** [/tmp/efivar/src/include/rules.mk:32: libefivar.so] Error 1
    make[1]: Leaving directory '/tmp/efivar/src'
    make: *** [Makefile:14: all] Error 2

Thanks,
Kevin

**Comment by sh4rknado** [comment]
same error on my LFS environement 


Distribution : Linux From Scratch
GCC Version : 10.2.0


GCC INFOS:
-----------------

(lfs chroot) root:/sources/efivar-37# gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-pc-linux-gnu/10.2.0/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: ../configure --prefix=/usr LD=ld --enable-languages=c,c++ --disable-multilib --disable-bootstrap --with-system-zlib
Thread model: posix
Supported LTO compression algorithms: zlib zstd
gcc version 10.2.0 (GCC) 


Error Build  : 
-----------------

(lfs chroot) root:/sources/efivar-37#     patch -Np1 -i ../efivar-37-gcc_9-1.patch
patching file src/dp.h
patching file src/dp-media.c
patching file src/dp-message.c
patching file src/dp-message.c
patching file src/dp.h
patching file src/guid.c
patching file src/include/efivar/efivar.h
patching file src/ucs2.h
(lfs chroot) root:/sources/efivar-37#     make libdir=/usr/lib
make[1]: Entering directory '/sources/efivar-37/src'
cc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -L.   -Wl,-z,muldefs     -DEFIVAR_BUILD_ENVIRONMENT -o makeguids makeguids.c guid.c -ldl 
./makeguids guids.txt guids.bin names.bin \
	guid-symbols.c include/efivar/efivar-guids.h
35 lines
make -f /sources/efivar-37/src/Make.deps deps SOURCES="crc32.c creator.c disk.c gpt.c loadopt.c path-helpers.c linux.c linux-acpi-root.c linux-acpi.c linux-ata.c linux-emmc.c linux-i2o.c linux-md.c linux-nvme.c linux-pci-root.c linux-pci.c linux-pmem.c linux-sas.c linux-sata.c linux-scsi.c linux-soc-root.c linux-virtblk.c dp.c dp-acpi.c dp-hw.c dp-media.c dp-message.c efivarfs.c error.c export.c guid.c guids.S guid-symbols.c lib.c vars.c makeguids.c guid.c include/efivar/efiboot-creator.h include/efivar/efiboot-loadopt.h include/efivar/efiboot.h include/efivar/efivar-dp.h include/efivar/efivar.h include/efivar/efivar-guids.h guid-symbols.c efivar.c"
make[2]: Entering directory '/sources/efivar-37/src'
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .crc32.d crc32.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .creator.d creator.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .disk.d disk.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .gpt.d gpt.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .loadopt.d loadopt.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .path-helpers.d path-helpers.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux.d linux.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-acpi-root.d linux-acpi-root.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-acpi.d linux-acpi.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-ata.d linux-ata.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-emmc.d linux-emmc.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-i2o.d linux-i2o.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-md.d linux-md.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-nvme.d linux-nvme.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-pci-root.d linux-pci-root.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-pci.d linux-pci.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-pmem.d linux-pmem.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-sas.d linux-sas.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-sata.d linux-sata.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-scsi.d linux-scsi.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-soc-root.d linux-soc-root.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .linux-virtblk.d linux-virtblk.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .dp.d dp.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .dp-acpi.d dp-acpi.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .dp-hw.d dp-hw.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .dp-media.d dp-media.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .dp-message.d dp-message.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .efivarfs.d efivarfs.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .error.d error.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .export.d export.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .guid.d guid.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .guid-symbols.d guid-symbols.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .lib.d lib.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .vars.d vars.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .makeguids.d makeguids.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .efivar.d efivar.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs   -MM -MG -MF .guids.d guids.S
make[2]: Leaving directory '/sources/efivar-37/src'
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o dp.o dp.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o dp-acpi.o dp-acpi.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o dp-hw.o dp-hw.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o dp-media.o dp-media.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o dp-message.o dp-message.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o efivarfs.o efivarfs.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o error.o error.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o export.o export.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o guid.o guid.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o guids.o guids.S
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o guid-symbols.o guid-symbols.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o lib.o lib.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -fPIC  -c -o vars.o vars.c
gcc -O2 -flto -g3 -I/sources/efivar-37/src/include/   -specs=/sources/efivar-37/gcc.specs  -L.   -Wl,-z,muldefs      -shared \
  -Wl,-soname,libefivar.so.1 \
  -Wl,--version-script=libefivar.map \
  -o libefivar.so dp.o dp-acpi.o dp-hw.o dp-media.o dp-message.o efivarfs.o error.o export.o guid.o guids.o guid-symbols.o lib.o vars.o -ldl 
/tmp/cc9D1ZVg.s: Assembler messages:
/tmp/cc9D1ZVg.s: Error: invalid attempt to declare external version name as default in symbol `efi_set_variable@@LIBEFIVAR_0.24'
lto-wrapper: fatal error: gcc returned 1 exit status
compilation terminated.
/usr/bin/ld: error: lto-wrapper failed
collect2: error: ld returned 1 exit status
make[1]: *** [/sources/efivar-37/Make.rules:20: libefivar.so] Error 1
make[1]: Leaving directory '/sources/efivar-37/src'
make: *** [Makefile:14: all] Error 2


Thanks,
Jordan B.

**Comment by kevinoid** [comment]
For reference, Debian addressed this issue by adding `-flto-partition=none` see [dd6614a from efi-team/efivar!5](https://salsa.debian.org/efi-team/efivar/-/merge_requests/5/diffs?commit_id=dd6614a15c5aa4e567dba48ecf338e3538d3f040).

**Comment by frozencemetery** [comment]
Fixed in c08bb8948f3f56f78b19d9f708cfeb3fcd3cc74d
