### ISSUE TITLE
XML ABI dumps are missing the variadic arguments

### ISSUE THREAD

**Issue by ppisar** [rhboot/efivar#165]
src/libefiboot.abixml and src/libefivar.abixml files miss variadic arguments. See e.g. efi_error_set() function. That's probably caused by a GCC bug <https://bugzilla.redhat.com/show_bug.cgi?id=1891787> that misses them if LTO is enabled.

That causes "make abicheck"  failure when efivar is built without LTO, and it will causes the same failre once GCC fixes the bug.

I don't think there is any good way of fixing the test until the gcc issue settles down. Take this report as a precaution, that things will start failing.

**Comment by ppisar** [comment]
For you reference, this is a patch that Fedora carries <https://src.fedoraproject.org/rpms/efivar/raw/master/f/0001-Fix-abidw-output-for-missing-variadic-arguments.patch>.

**Comment by frozencemetery** [comment]
If you have a patch for something, open a PR, not an issue.  (For that matter, don't provenpackager things into other people's packages without talking to them first - it goes against Fedora policy.)  At this point I suspect it no longer applies to development head, but please correct me if that's not the case.

**Comment by ppisar** [comment]
I was asked to fix the build failure in Fedora, so I did it. I reported the issue here because you could be interested in it. I don't send the patch because it was only a temporary regression in GCC. Thanks for positive and welcoming reaction a year after.
