### ISSUE TITLE
Fails to build with GCC 9.3.0

### ISSUE THREAD

**Issue by andypoo** [rhboot/efivar#167]
The compatibility attempted to be introduced in ea66c589340eac9a0d9f8a998f645752b654b719 does not work as the symbol for _efi_set_variable_mode, etc are now after the VERSION.

**Comment by CalamariAce** [comment]
I have the same problem.

**Comment by playday3008** [comment]
Try to include efivar headers using
```cpp
extern "C" {
    #include <efivar/efivar.h>
}
```

**Comment by frozencemetery** [comment]
Fixed in c08bb8948f3f56f78b19d9f708cfeb3fcd3cc74d
