### ISSUE TITLE
Invalid free on import

### ISSUE THREAD

**Issue by nvzoll** [rhboot/efivar#173]
Build environment: Linux Mint 20, gcc 9.3.0
Revision: https://github.com/rhboot/efivar/commit/cff88dd96b9d43e2c5875a24ba6180b196890ded
```
>./efivar -n <GUID-Name> -e var.bin
> ./efivar -i var.bin
free(): invalid pointer
[1]    2482 abort (core dumped)    ./efivar -i var.bin
```

From what I understand, [this free](https://github.com/rhboot/efivar/blob/master/src/efivar.c#L680) tries to free the memory allocated with mmap [here](https://github.com/rhboot/efivar/blob/master/src/efivar.c#L451).

**Comment by frozencemetery** [comment]
Links are very dead at this point.  Does this still happen, and if so can you point at where the code is (by functionname)?

**Comment by nvzoll** [comment]
Sorry, here are the links on the particular commit.
This free:
https://github.com/rhboot/efivar/blob/cff88dd96b9d43e2c5875a24ba6180b196890ded/src/efivar.c#L680
tries to free the memory allocated with mmap here:
https://github.com/rhboot/efivar/blob/cff88dd96b9d43e2c5875a24ba6180b196890ded/src/efivar.c#L451

**Comment by frozencemetery** [comment]
`free(data)` in main() IMPORT non-EXPORT case.

Allocation the mmap() in prepare_data().
