### ISSUE TITLE
sys/cdefs.h missing on musl

### ISSUE THREAD

**Issue by oxr463** [rhboot/efivar#197]
In https://github.com/rhboot/efivar/commit/62afa2aa588fb0a6ff56acdd268b9f3c557028b8 `#include <sys/cdefs.h>` was added to `src/compiler.h`. This header is not included in musl libc.

**Comment by oxr463** [comment]
I took that line out:

```
sed -i src/compiler.h
```

This is the only error I see:

```
efisecdb.c: In function 'main':
efisecdb.c:379:2: warning: implicit declaration of function 'on_exit'; did you mean '_exit'? [-Wimplicit-function-declaration]
  379 |  on_exit(free_actions, &actions);
      |  ^~~~~~~
      |  _exit
```

**Comment by floppym** [comment]
The `on_exit` function appears to be glibc-specific.
https://www.gnu.org/software/libc/manual/html_node/Cleanups-on-Exit.html
