### ISSUE TITLE
Multiple definitions  "efi_set_variable"   in utf8len funtion ?

### ISSUE THREAD

**Issue by angelllls** [rhboot/efivar#82]
shell:  
      $ cp -p Make.defaults Make.defaults.dist
        $ sed 's|-O2|-Os|g' -i Make.defaults
        $ cp -p src/test/Makefile src/test/Makefile.dist
        $ sed 's|-rpath=$(TOPDIR)/src/|-rpath=$(libdir)|g' \
        $ -i src/test/Makefile
        $ make libdir="/usr/lib/" bindir="/usr/bin/" \
        $ mandir="/usr/share/man/"     \
        $ includedir="/usr/include/" V=1 -j1
:
-Wl,--version-script=libefivar.map \
  -o libefivar.so dp.o dp-acpi.o dp-hw.o dp-media.o dp-message.o efivarfs.o error.o export.o guid.o guids.o guid-symbols.o lib.o vars.o -ldl 
/tmp/ccJxKHhA.ltrans0.ltrans.o：在函数‘utf8len’中：
/sources/efivar-30/src/ucs2.h:53: efi_set_variable 的多重定义
/tmp/ccJxKHhA.ltrans0.ltrans.o:/sources/efivar-30/src/lib.c:77：第一次在此定义
collect2: error：ld return 1
make[1]: *** [/sources/efivar-30/Make.rules:20：libefivar.so] error 1
make[1]: 离开目录“/sources/efivar-30/src”
make: *** [Makefile:11：all] error 2

**Comment by vathpela** [comment]
Can you reproduce this with efivar 31?  I *think* all the instances of this should be fixed in the current tree.

**Comment by vathpela** [comment]
I'm going to assume this means no; please reopen if it comes back.
