### ISSUE TITLE
dlopen/dlysm usage

### ISSUE THREAD

**Issue by ikeydoherty** [rhboot/efivar#93]
The guid.c code is .. puzzling, to say the least.

efivar supports a static build target, so I'm curious as to why `dlopen` + `dlysm` are being used? With glibc that generates a compiler warning, and other libcs would not like that in the least..

**Comment by vathpela** [comment]
It's using dlopen()+dlsym() to get the built-in list of guids at runtime, so we don't have to keep two lists that can become out of sync.  dlopen(NULL, ...) returns the handle for the binary that called dlopen() (i.e. not some other library on disk or something).  This is a standard use of the API, and in no way effects static linking.
