### ISSUE TITLE
efibootmgr fails to set the timeout

### ISSUE THREAD

**Issue by Sivasakthivel** [rhboot/efivar#95]
[root@localhost ~]# efibootmgr -t 10
Could not set Timeout: Invalid argument

efibootmgr uses efivar to set the EFI global variable timeout.  When tries to set the  value,   this github code tries to delete the variable.  UEFI firmware returns a error  EFI_WRITE_PROTECTED  since it has this variable has the   default value. 

 efivar  may need to set the variable without deleting or  honor the  return status of the delete request

**Comment by vathpela** [comment]
There's no such thing as "set the variable without deleting".  There are only three operations: set, unset, append.  To change a value we have to remove and create again.

If the system firmware isn't letting you do that, there's nothing we can do about it.

That said, there's some chance you've upgraded your kernel but you still have a (very) old build of libefivar, and the immutable flag is set on the variable?  If so, you just need a newer libefivar.
